# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: clear-credentials
        name: clear-credentials
        files: secrets.h
        stages: [commit]
        language: system
        entry: /bin/sed -i -e 's/\".*\"[ ]*/\"XXXXXX\"  /'
